### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by agarzon**
Updated codeception to latest version.

### CODE REVIEW

**Comment by agarzon** [comment]
As you can see, Travis fails because the same issue reported previously https://github.com/cakephp/codeception/issues/37

**Comment by lorenzo** [comment]
@agarzon do you know a way for fixing this?

**Comment by agarzon** [comment]
No yet :(

Seems like a collision problem with _symfony/console_

**Comment by lorenzo** [comment]
Can we change the restriction for the console package?

**Comment by agarzon** [comment]
Don't think so, since that package is required by codeception composer.

https://github.com/Codeception/Codeception/blob/2.2/composer.json

I guess one possible solution could be change our composer.json and remove codeception as required or moved to _require-dev_ or _suggest_

**Comment by freemanchari** [comment]
Any movement on this?

**Comment by Naktibalda** [comment]
You could fix the build by executing `composer require --prefer-source --dev cakephp/codeception:dev-$TRAVIS_BRANCH#$TRAVIS_COMMIT` before `composer install`

**Comment by Naktibalda** [comment]
Sorry, that won't help, symfony/console 3.1.5 is installed by `create-project`.
Anyway, the problem is that this project has a dependency on Codeception 2.0 which does not support Symfony 3, all you have to do is to update to Codeception 2.2 which does.

It is odd that PR which changes required version of Codeception to 2.2 fails by trying to install Codeception 2.0.16.
>    - cakephp/codeception dev-master requires codeception/codeception ~2.0.16 -> satisfiable by codeception/codeception[2.0.16, 2.0.x-dev].

**Comment by agarzon** [comment]
closing, this issue is freaking old.

**Pull request closed without merging**
