### PR TITLE
Update to Codeception 2.3, Support PSR-7 dispatcher

### PR DESCRIPTION
**Pull request by nojimage**
- Update to Codeception 2.3
- Support PSR-7 dispatcher (CakePHP ^3.4)
- Installer no longer replace `Build`, `GenerateGroup` command.
- `Bootstrap` command generate suite configuration with `suite_namespace`.
- Acceptance suite no longer load `Cake\Codeception\Helper`
- Fixture loading logic move to `FixtureTrait`, and backports [nojimage/codeception-cakefixture](https://github.com/nojimage/codeception-cakefixture)
- improve .travis-ci
   - CakePHP 3.1 with PHP 5.4
   - CakePHP 3.2 with PHP 5.5
   - CakePHP 3.3 with PHP 5.5
   - CakePHP 3.4, 3.5 with PHP 5.6, 7.0, 7.1

### CODE REVIEW

**Comment by lorenzo** [comment]
Wow, Thanks!

I'll review shortly, and get this merged

**Comment by lorenzo** [comment]
The diff is big, so the chances that I missed something are high, but in general it looks solid. I'll merge this.

Any chance you could write something short about using this new version?

**Comment by nojimage** [comment]
Thanks review and merge PR.

I noticed now that the `loadFixtures` method does not work as documented because I changed around the fixture.
(It works like CakePHP TestCase, and it works only with `Cest`, Fixture can not be used on `Cept`.

Also, since the arrangement of helper files has changed, you have to change the README.
I will send PR.

**Comment by nojimage** [comment]
One more, I changed do not load `Cake\Codeception\Helper` In the Acceptance test, beacase that conflict with WebDriver or PhpBrowser module.

**Pull request merged**
